# The empty Miranda extras configuration has nothing in it and should not.
# It is meant to override the default to add custom control parameters
# file in your own Miranda customization package and setting MIRANDS_CONFIG_EXTRAS
# to your customization file in the launch file control.launch.
# Each parameter will need to be loaded in the correct namespace to
# be used. 